### ISSUE TITLE
downloads limits size menu highligh is not in sync with text

### ISSUE THREAD

**Issue by hellfreezeover** [kkffiirr/MIUI7_Hebrew#13]
the menu in downloads-->settings is not highlighted properly (UMI Zero):
![screenshot_com android providers downloads ui_2015-09-25-13-51-49](https://cloud.githubusercontent.com/assets/13970559/10099032/abb4702e-638e-11e5-9530-67e6464342d8.png)

**Comment by kkffiirr** [comment]
only because you use custom font

**Comment by hellfreezeover** [comment]
Well,
It also happens in the default theme...
I also have 3 missing ICONS on the default theme (Clock, Weather... )
I'm re-opening this

**Comment by kkffiirr** [comment]
Try it in English mode, does it happens?

**Comment by hellfreezeover** [comment]
In English as well...

**Comment by kkffiirr** [comment]
SoSo, it is not related to our translation, it is general miubug. ug

**Comment by hellfreezeover** [comment]
Probably,
As this is a port Rom from Redmi 3G MTK.
I thought you guys may know how to fix...

**Comment by kkffiirr** [comment]
It is not in our scope.
You can try to mess with the xml files, you might get some progress, and
then we will be happy to support
