### ISSUE TITLE
In dial screen - Dial pad buttons overlaped (First Redmi/Hongmi)

### ISSUE THREAD

**Issue by eladbs** [kkffiirr/MIUI7_Hebrew#15]
Hi,

In the latest version 5.10.8 there is still a problem with the dialing numbers being overlapped by the options in the dial screen.

Please fix it... :)
Thanks!
Elad.

**Comment by kkffiirr** [comment]
Which phone?

**Comment by eladbs** [comment]
Hi,

The device I meant (and is written in the title...) is the first hongmi/redmi a.k.a HM2013023.
The one with the mt6589 SOC.

I looked at the XMLs and everything seems to be the same as the other phones, which do work...

Thanks!

**Comment by kkffiirr** [comment]
Fixed

**Comment by eladbs** [comment]
Thanks!!
