### ISSUE TITLE
Dial pad while answering a call can not be reached

### ISSUE THREAD

**Issue by shaulsu** [kkffiirr/MIUI7_Hebrew#7]
Hi,
Device REDMI 2(Model 813) - Language - Hebrew

When you dail and some one answered can be open the dial pad because the icons is one in the other.
was fixed in previous version 5.8.27 and now spoiled again
![f9c69a92-4d97-11e5-99a0-48d8d4069ef4](https://cloud.githubusercontent.com/assets/14050615/9657929/0cef6530-524e-11e5-9b24-7f40a6dd42a2.png)

**Comment by eliran0216** [comment]
תנסה את התיקון למכשיר שלך כאן
http://iandroid.co.il/forum/viewtopic.php?p=1551933#p1551933

**Comment by shaulsu** [comment]
תודה אלירן
לקחתי בנתיים מגרסא 5.8.27 את 
Incallui.apk
