### ISSUE TITLE
Dial pad on a call not working - redmi note 2

### ISSUE THREAD

**Issue by zur250** [kkffiirr/MIUI7_Hebrew#8]
i just recieved the phone , and there is this bug.
is it fixed yet? if so can you give me the link to the download pls?
just to be sure i am talking about XIAOMI REDMI NOTE 2 device.
thanks a lot for the help!

**Comment by eliran0216** [comment]
תתקין את הגירסה הזאת דרך ה updater
https://www.androidfilehost.com/?fid=24052804347808405
ותחליף את הקובץ incallui שנמצא בתיקיית system/priv-app 
בזה
https://mega.nz/#!AAQm1KpI!vyPn6Ss6yi-ZKDCX1YeNDlE1NZ8SatFYVxZtgYpAUDk
עם האפליקצייה root browser(תאשר גישת רוט)
לאחר ההחלפה תפעיל מחדש

**Comment by zur250** [comment]
תגיד את הroot brower אני צריך לעשות לפני כל העידכונים או אחרי?


נשלח מסמארטפון ה-Samsung Galaxy שלי.

<div>-------- הודעה מקורית --------</div><div>מאת: eliran0216 <notifications@github.com> </div><div>תאריך:06/09/2015  22:02  (GMT+02:00) </div><div>אל: kkffiirr/MIUI7_Hebrew <MIUI7_Hebrew@noreply.github.com> </div><div>עותק: zur250 <zur1995@gmail.com> </div><div>נושא: Re: [MIUI7_Hebrew] Dial pad on a call not working - redmi note 2 (#8) </div><div>
</div>תתקין את הגירסה הזאת דרך ה updater
https://www.androidfilehost.com/?fid=24052804347808405
ותחליף את הקובץ incallui שנמצא בתיקיית system/priv-app 
בזה
https://mega.nz/#!AAQm1KpI!vyPn6Ss6yi-ZKDCX1YeNDlE1NZ8SatFYVxZtgYpAUDk
עם האפליקצייה root browser(תאשר גישת רוט)
לאחר ההחלפה תפעיל מחדש

**Comment by eliran0216** [comment]
אתה לא צריך לעשות את התיקון
כי בעדכון החדש זה כבר תוקן

**Comment by zur250** [comment]
זה עידכון שאתה הכנת או שהחברה עצמה עשתה? אם זה החברה איך אני מעדכן את
המכשיר?
בתאריך 16 בספט 2015 09:40, "eliran0216" <notifications@github.com> כתב:

**Comment by eliran0216** [comment]
זה עדכון מהחברה שתוריד מ xiaomi.eu
מדריך
http://m.imgur.com/a/w0uCH

**Comment by zur250** [comment]
הי
אני עוקב אחר המדריך אבל לא ניתן להתקין את העדכון.
לא צריך איכשהו להשתמש בupdater הזה?

בתאריך 16 בספטמבר 2015 בשעה 9:50, מאת eliran0216 <notifications@github.com>:
